# Generated by Django 4.2.1 on 2023-07-17 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DeductionCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deduction_code', models.CharField(max_length=250, unique=True)),
                ('code', models.CharField(choices=[('837472786', '837472786'), ('847373475', '837373475'), ('853748262', '853748262')], default='837472786', max_length=20)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('RTGS', 'RTGS'), ('RAND', 'RAND')], max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='company_codes', to='Company.company')),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(db_index=True, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('CANCELED', 'CANCELED'), ('DRAFT', 'DRAFT'), ('FAILED', 'FAILED'), ('PROCESSED', 'PROCESSED'), ('PROCESSING', 'PROCESSING'), ('SUCCESS', 'SUCCESS'), ('SENT', 'SENT'), ('SAVED', 'SAVED')], default='DRAFT', max_length=15)),
                ('paymaster', models.CharField(default='SSB', max_length=20)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_sent', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='company_batches', to='Company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_batches', to=settings.AUTH_USER_MODEL)),
                ('deduction_code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='deduction_code_batches', to='Batch.deductioncode')),
            ],
            options={
                'ordering': ['-date_created'],
                'indexes': [models.Index(fields=['-date_sent'], name='Batch_batch_date_se_f0d61f_idx')],
            },
        ),
    ]
