# Generated by Django 4.2.1 on 2023-06-25 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeductionCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deduction_code', models.CharField(max_length=250, unique=True)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('RTGS', 'USD'), ('RAND', 'RAND')], max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='company_codes', to='Company.company')),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(db_index=True, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('Sent', 'Sent'), ('Processing', 'Processing'), ('Processed', 'ProcesSED'), ('Pending', 'Pending')], default='Pending', max_length=15)),
                ('paymaster', models.CharField(default='SSB', max_length=20)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_sent', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_batches', to=settings.AUTH_USER_MODEL)),
                ('deduction_code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='deduction_code_batches', to='Batch.deductioncode')),
            ],
            options={
                'ordering': ['-date_created'],
                'indexes': [models.Index(fields=['-date_sent'], name='Batch_batch_date_se_f0d61f_idx')],
            },
        ),
    ]
